name: queries
version: 0.1.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Enumerable collections for Dart language (inspired by Microsoft LINQ).
homepage: https://github.com/mezoni/queries
environment:
  sdk: '>=2.0.0-dev.60.0 <3.0.0'
dependencies:
  function_types: '>=0.0.1 <=1.0.0'
dev_dependencies:
  build_tools: any
  file_utils: any
  test: any
