name: queries
version: 0.1.8
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Enumerable collections for Dart language (inspired by Microsoft LINQ).
homepage: https://github.com/mezoni/queries
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  function_types: '>=0.0.1 <=1.0.0'
dev_dependencies:  
  #test: ^1.5.2
  test: any
