name: queries
version: 0.1.4
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Enumerable collections for Dart language (inspired by Microsoft LINQ).
homepage: https://github.com/mezoni/queries
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  function_types: '>=0.0.1 <=1.0.0'
dev_dependencies:
  build_tools: ^0.1.0
  file_utils: ^0.1.1
  test: ^1.3.0
