name: queries
author: Andrew Mezoni <andrew.mezoni@gmail.com>
version: 0.0.12
homepage: https://github.com/mezoni/queries
description: Queryable collections for Dart language.
dependencies:
  reflection: any
dev_dependencies:
  unittest: any
